"""griot init command.

Scaffold a new ODCS-format data contract.

SDK Method: None (pure scaffolding, no business logic)
Status: Complete (T-363)
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

import click

from griot_cli.output import echo_error, echo_info, echo_success


# ODCS contract template - follows example_contract.yaml structure
ODCS_TEMPLATE = """\
# =============================================================================
# Griot Data Contract - Open Data Contract Standard (ODCS) v1.0.0
# Generated by: griot init
# =============================================================================

api_version: v1.0.0
kind: DataContract
id: {contract_id}
name: {name}
version: 1.0.0
status: draft

description:
  purpose: {purpose}
  usage: |
    Describe how this data should be used.
  limitations: |
    Document any known limitations or caveats.
  customProperties: []

schema:
  - name: {schema_name}
    physicalType: table
    properties:
      - name: id
        description: Primary identifier
        logicalType: string
        physicalType: VARCHAR(36)
        nullable: false
        primary_key: true
        constraints:
          pattern: "^[a-zA-Z0-9-]+$"
          max_length: 36
        semantic:
          description: Unique identifier for each record
          business_term: identifier
        privacy:
          contains_pii: false
          sensitivity_level: internal

      # Add more fields here following the same structure

    quality:
      - rule: completeness
        min_percent: 99.0
        critical_fields:
          - id
      - rule: freshness
        max_age: PT24H
        timestamp_field: updated_at

legal:
  jurisdiction:
    - {jurisdiction}
  basis: legitimate_interest
  regulations: []
  cross_border:
    restrictions: []
    transfer_mechanisms: []

compliance:
  data_classification: internal
  regulatory_scope: []
  audit_requirements:
    logging: true
    log_retention: P365D
  export_restrictions:
    allow_download: false
    allow_external_transfer: false

sla:
  availability:
    target_percent: 99.0
    measurement_window: P30D
  freshness:
    target: P1D
  completeness:
    target_percent: 99.5

access:
  default_level: internal
  grants: []
  approval:
    required: false
    approvers: []
  authentication:
    methods:
      - api_key

distribution:
  channels: []

governance:
  producer:
    team: {team}
    contact: {contact}
    responsibilities:
      - Maintain data quality
      - Provide timely updates
      - Address consumer questions
  consumers: []
  approval_chain: []
  review:
    cadence: quarterly
  change_management:
    breaking_change_notice: P30D
    deprecation_notice: P90D
    communication_channels: []
    migration_support: true
  documentation:
    wiki: ""
    runbook: ""
    changelog: ""

team:
  name: {team}
  department: ""
  steward:
    name: ""
    email: {contact}

servers: []

roles: []

timestamps:
  created_at: {created_at}
  updated_at: {updated_at}
"""


@click.command()
@click.argument("name", required=True)
@click.option(
    "--output",
    "-o",
    type=click.Path(path_type=Path),
    default=None,
    help="Output file path (default: <name>.yaml in current dir).",
)
@click.option(
    "--id",
    "contract_id",
    type=str,
    default=None,
    help="Contract ID (default: generated from name).",
)
@click.option(
    "--purpose",
    "-p",
    type=str,
    default="Describe the purpose of this data contract.",
    help="Purpose description for the contract.",
)
@click.option(
    "--team",
    "-t",
    type=str,
    default="Data Team",
    help="Team responsible for this contract.",
)
@click.option(
    "--contact",
    type=str,
    default="team@example.com",
    help="Contact email for the team.",
)
@click.option(
    "--jurisdiction",
    "-j",
    type=str,
    default="US",
    help="Primary jurisdiction (e.g., US, EU, UK).",
)
@click.option(
    "--force",
    "-f",
    is_flag=True,
    help="Overwrite existing file.",
)
@click.pass_context
def init(
    ctx: click.Context,
    name: str,
    output: Path | None,
    contract_id: str | None,
    purpose: str,
    team: str,
    contact: str,
    jurisdiction: str,
    force: bool,
) -> None:
    """Initialize a new ODCS-format data contract.

    NAME is the human-readable name for the contract.

    Creates a new contract file with ODCS structure including:
    - Contract metadata (api_version, kind, id, version, status)
    - Description section
    - Schema section with example field
    - Quality rules (completeness, freshness)
    - Legal and compliance sections
    - SLA definitions
    - Access control
    - Governance structure
    - Team information
    - Timestamps

    Exit codes:
      0 - Contract created successfully
      1 - File already exists (use --force to overwrite)
      2 - Error

    Examples:
      griot init "Customer Profile"
      griot init "Order Events" -o contracts/orders.yaml
      griot init "User Data" --team "Analytics" --jurisdiction EU
    """
    try:
        # Generate contract ID from name if not provided
        if contract_id is None:
            contract_id = name.lower().replace(" ", "-").replace("_", "-")
            # Remove any non-alphanumeric characters except hyphens
            contract_id = "".join(c for c in contract_id if c.isalnum() or c == "-")

        # Determine output path
        if output is None:
            output = Path(f"{contract_id}.yaml")

        # Check if file exists
        if output.exists() and not force:
            echo_error(f"File already exists: {output}")
            echo_info("Use --force to overwrite.")
            sys.exit(1)

        # Generate timestamps
        now = datetime.now(timezone.utc).isoformat()

        # Generate schema name from contract name
        schema_name = name.lower().replace(" ", "_").replace("-", "_")

        # Fill in template
        content = ODCS_TEMPLATE.format(
            contract_id=contract_id,
            name=name,
            purpose=purpose,
            schema_name=schema_name,
            team=team,
            contact=contact,
            jurisdiction=jurisdiction,
            created_at=now,
            updated_at=now,
        )

        # Create parent directories if needed
        output.parent.mkdir(parents=True, exist_ok=True)

        # Write file
        output.write_text(content, encoding="utf-8")

        echo_success(f"Created contract: {output}")
        echo_info(f"  ID: {contract_id}")
        echo_info(f"  Name: {name}")
        echo_info(f"  Team: {team}")
        echo_info("")
        echo_info("Next steps:")
        echo_info(f"  1. Edit {output} to add your schema fields")
        echo_info("  2. Run 'griot lint' to check for issues")
        echo_info("  3. Run 'griot push' to publish to registry")

    except PermissionError as e:
        echo_error(f"Permission denied: {e}")
        sys.exit(2)
    except Exception as e:
        echo_error(f"Error: {e}")
        sys.exit(2)
